### ISSUE TITLE
Upgrade to 0.22.1

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/zeebe-test-container#21]
Upgrade to Zeebe 0.22.1.

**Comment by grexe** [comment]
please update for 0.22.1, I have a PR ready but still issues with unit tests timing out on containers in cluster tests.

**Comment by npepinpe** [comment]
I think I ran into similar issues, I'll look into it once I'm back from my holidays. Thanks for your contribution!

**Comment by grexe** [comment]
Interestingly, the tests all ran through here, so it's maybe another Docker on Mac issue...

**Comment by npepinpe** [comment]
The tests can be a little heavy docker wise, I suppose, and Docker on Mac is always special :sweat_smile:

**Comment by npepinpe** [comment]
Closed by #35
